### ISSUE TITLE
Migrate RD_ macros to CD_ macros from ColorDebug

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#57] opened 2016-06-22 18:19 UTC
Migrate RD_ macros to CD_ macros from [ColorDebug](https://github.com/jgvictores/ColorDebug).

**Comment by PeterBowman** [comment] 2018-02-12 16:19
Duplicate of #123.

**Closed by PeterBowman** 2018-02-12 16:19 UTC
Labels: duplicate, priority: idea
